name: SemgrepPublish
jobs:
  semgrep:
    name: Publish
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - run: semgrep publish --visibility=org_private 
